#jQuery(function() {
#  return $('#events-raw-data').dataTable({
#    asSorting: [['0', 'desc']],
#    aaSorting: [['0', 'desc']],
#    sPaginationType: "full_numbers"
#  });
#});
# // generated by coffee-script 1.9.2
# coffee script follows:

jQuery ->
  $('#events-raw-data').dataTable
    asSorting: [['0','desc']]
    aaSorting: [['0','desc']]
    sPaginationType: "full_numbers"
